mapnik/node-mapnik

- binding.gyp
Closes #74 
Passes on appveyor: https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.135
> Try removing FORCE:MULTIPLE - refs #74

- bin/mapnik-shapeindex.js
- lib/mapnik.js
- package.json
- test/mapnik-shapeindex.test.js
Fixes #378, but only a `shapeindex` script. `nik2img` remains "hidden".
cc @springmeyer
> Add mapnik-shapeindex script

- scripts/build_against_sdk.sh
- src/ds_emitter.hpp
> A small set of changes that should fix Ref #373

- .travis.yml
- package.json
- src/ds_emitter.hpp
This will be okay to merge once passing and after the node v3.1.5 release is out (since we've already tested upcoming v3.1.5 heavily) and this needs more testing to make sure the Nan upgrade does not create any issues.
/cc @flippmoke
> io.js and node v0.12.x support

- package.json
> add iojs version to engine

- src/mapnik_vector_tile.cpp
> Fix broken visitor on windows

- src/mapnik_vector_tile.cpp
- test/vector-tile.test.js
> Added GeoJSON buffer to VectorTile.addGeoJSON.

- src/mapnik_image.cpp
- src/mapnik_image.hpp
- test/image.test.js
> Save Image Async

- src/mapnik_image.cpp
- src/mapnik_image.hpp
- test/image.filter.test.js
- test/image.svg.test.js
- test/logger.test.js
closes #502 
/cc @springmeyer for review
> Added the ability to modify an image via an image filter

- .travis.yml
- CHANGELOG.md
- appveyor.yml
- package.json
- src/mapnik_image.cpp
- src/mapnik_image.hpp
- test/image.test.js
Adds the ability to create an image from a buffer object as to not copy memory. 
/cc @springmeyer @bsudekum
> Image zero alloc

- src/mapnik_image.cpp
Fixes #574
/cc @springmeyer @flippmoke
> document mapnik.Image.data()

- .travis.yml
- package.json
- src/mapnik_feature.cpp
- src/mapnik_image.cpp
- src/mapnik_logger.cpp
- src/mapnik_vector_tile.cpp
> Add support for Node v6

- src/mapnik_image.cpp
- test/image.test.js
> Persist image buffer in fromBufferSync

- .travis.yml
Adds a job to travis that tests building with g++-5.
Refs #389
> Test building with g++-5

- binding.gyp
- package.json
- src/mapnik_vector_tile.cpp
Upgrades to protozero v1.4.2. Refs https://github.com/mapbox/mapnik-vector-tile/pull/222
> Protozero v1.4.2

- src/mapnik_map.cpp
Docs describing the input/output of `Map#queryPoint` and `Map#queryMapPoint`
refs: #701
cc @springmeyer @flippmoke @artemp
> add docs for Map#queryPoint and Map#queryMapPoint

- .gitmodules
- binding.gyp
- install_mason.sh
- package.json
Update the dependencies in a way such that windows builds will still be possible.
> Dependency update for Windows

- scripts/build_against_sdk_03-write-mapnik.settings.ps1
- scripts/postinstall.sh
- test/constants.test.js
Added the path variables to `mapnik_settings.js` creation. I was unsure if `gen_settings.py` also needed to be changed as well.
/cc @springmeyer
> Shape-Index and Mapnik-Index path variables

- CHANGELOG.md
- install_mason.sh
- package.json
> Updated to use mapnik 3.0.15

- src/mapnik_color.cpp
- src/mapnik_datasource.cpp
- src/mapnik_feature.cpp
- src/mapnik_featureset.cpp
- src/mapnik_geometry.cpp
- src/mapnik_grid_view.cpp
- src/mapnik_image.cpp
- src/mapnik_image_view.cpp
- src/mapnik_layer.cpp
- src/mapnik_map.cpp
- src/mapnik_memory_datasource.cpp
- src/mapnik_vector_tile.cpp
> fix node v0.10.x 

- package.json
- scripts/build-appveyor.bat
- src/mapnik_color.cpp
- src/mapnik_datasource.cpp
- src/mapnik_feature.cpp
- src/mapnik_featureset.cpp
- src/mapnik_geometry.cpp
- src/mapnik_grid_view.cpp
- src/mapnik_image.cpp
- src/mapnik_image_view.cpp
- src/mapnik_layer.cpp
- src/mapnik_map.cpp
- src/mapnik_memory_datasource.cpp
- src/mapnik_vector_tile.cpp
Want to drop node v0.10.x soon. This is a last gasp attempt to keep it working for one more release.
refs https://github.com/mapbox/node-sqlite3/commit/354d688905613adf7e3bbb76eaade614990c8e3a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
> attempt to fix node v0.10.x support

- README.md
Small typo - missing space in README.md.
> Missing space in README.md

- .travis.yml
- Makefile
- test/vector-tile.test.js
Add SSE_MATH=false to travis, fix use of SSE_MATH false to work properly
> Fix SSE 3.0.x branch

- package.json
- scripts/install_deps.sh
- scripts/setup.sh
Per https://github.com/mapnik/mapnik/releases/tag/v3.0.20
cc @flippmoke @springmeyer
> Mapnik 3.0.20

- .travis.yml
Removing encrypted tokens from the .travis.yml file -> these are now stored as env variables in travis and have been rotated.
cc @springmeyer @artemp @flippmoke @millzpaugh @GretaCB @allieoop
> remove encrypted tokens

- .travis.yml
- package.json
- src/utils.hpp
- test/vector-tile.test.js
Master sync from https://github.com/mapnik/node-mapnik/pull/872
> Node 10 compatibility

- src/mapnik_image.cpp
- test/image.svg.test.js
> [master] Fix behavior of SVG parsing

- .travis.yml
- package.json
- scripts/install_deps.sh
- scripts/postgis/setup.sh
- scripts/postinstall.sh
- scripts/setup.sh
- test/data/postgis_datasource_tokens_query.xml
This PR:
- updates to latest mapnik 3.1.x (also might be called 4.x when released)
- fixes a few issues with the postgis tests
> Fixes to master branch (future 4.x)

- README.md
README should specify what package to install so developers can use this in their project.
```
npm install
```
alone doesn't say much.
> readme update: specifying the package to install

- src/blend.cpp
- src/blend.hpp
- src/tint.hpp
- test/blend.test.js
Added the ability to pass mapnik Image objects to Blend method.
> Blend Mapnik Image objects

- CHANGELOG.md
- src/mapnik_map.cpp
- src/mapnik_map.hpp
- test/map.test.js
This fixes https://github.com/mapnik/node-mapnik/issues/467. Tests are missing.
> Add Map.remove_layer method

- src/blend.cpp
- src/mapnik_image.cpp
Fixes a few small copy and paste errors introduced by the Node 12.x fixes.
> Fix some issues introduced by Node 12.x fixes

- package.json
And bump this package's version to `4.3.1`
> Update mapnik_version to a0ea7db1a

- .travis.yml
- CHANGELOG.md
> Drop support for Node < 10

- CHANGELOG.md
- package.json
- src/blend.cpp
- src/blend.hpp
- ensure `mapnik.Image` data is valid during `AsyncWorker::Execute()`
> node-mapnik v4.5.4

- CHANGELOG.md
- package.json
- scripts/install_deps.sh
- scripts/setup.sh
- test/image.svg.test.js
> Node mapnik v4.5.8

- src/mapnik_map.cpp
- test/map.test.js
Require width and height to be positive finite Number convertible to `std::int32_t` 
ref #990
> Map ctor - width/height validation 
