bin/mapnik-shapeindex.js
package.json

jshint doesn't do its own globbing, so when you run it on windows you have to specify folders, or else specific files.

jshint specific files

---

package.json
src/json_proj_transform_grammar.cpp
src/mapnik_geometry.cpp
src/mapnik_vector_tile.cpp
src/proj_transform_adapter.hpp

Adapt to advances upstream in Mapnik which allow geometries to be immutable (https://github.com/mapnik/mapnik/pull/2688) and safer to share across threads.

Vertex adapter

---

src/ds_emitter.hpp
src/mapnik_datasource.cpp
src/mapnik_datasource.hpp
src/mapnik_memory_datasource.cpp
src/mapnik_memory_datasource.hpp
test/datasource.test.js

This change addresses #431, and exposes datasource fields directly via a `fields()` method.  This should allow Mapbox Studio to retrieve just the fields it needs without incurring some other potentially expensive side-effects of calling `describe()` on the datasource.

Expose datasource fields directly

---

package.json
src/mapnik_vector_tile.cpp
test/vector-tile.test.js

This pull request enables toJSON to provide decoded geometry information rather then just the zig zag encoded integer data.

Added a new way for toJSON return decoded geometries

---

.travis.yml
appveyor.yml
bin/mapnik-index.js
scripts/build_against_sdk.sh
scripts/build_against_sdk_02-copy-deps-to-bindingdir.ps1
test/mapnik-index.test.js

- Now bundling the C++ `mapnik-index` command, written by @artemp and able to spatially index CSV and GeoJSON files (maybe more formats in the future)
- Adds tests for it and a wrapper (the wrapper is mainly designed to make it seamless to unit test both "packaged binaries" that bundle the command and source-installed node-mapnik's that have the tool on the PATH).
/cc @GretaCB @artemp

Start bundling mapnik-index command

---

package.json
src/mapnik_vector_tile.cpp
src/mapnik_vector_tile.hpp
test/vector-tile.query.test.js

Currently `vtile.query` returns an array of features with custom properties added:
- distance
- layer name
@ingalls would also like to know the corresponding x,y that was matched for a given search.
The meaning of that `x,y` would differ per geometry type:
- Point: the actual x,y of the single point
- MultiPoint: the x,y of the single point within the multipoint that is closest to the query x,y
- LineString: the vertex closest to the query x,y
- MultiLinestring: the vertex closest to the query x,y for the geometry part closest to the query x,y
- Multi(Polygon): not supported (since we don't support distance)
This pull starts sketching this out.
TODO:

Return x,y hit for vtile.query

---

package.json
src/mapnik_image.cpp
test/image.test.js

- Adds testcases (async + sync) for ensuring resize generates identical output when run repeatedly/at concurrency. See test only branch fail against master here: https://github.com/mapnik/node-mapnik/compare/resize-garbage-testcase?expand=1
- @springmeyer's fix by initializing the dest image
cc @springmeyer for your review

[notready] Init before resize

---

src/tint.hpp

Equality comparisons of floating point numbers are always dangerous and this case the code was actually failing on x86 with gcc 6 because one side of the comparison was still in a register and hence had 80 bit precision while the other side had been stored to memory and reduced to 64 bit precision:
https://bugzilla.redhat.com/show_bug.cgi?id=1303315
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69570

Avoid equality comparisons of floating point numbers

---

src/mapnik_vector_tile.cpp
test/image.test.js
test/map_generation.test.js
test/vector-tile.test.js

final VT tests

---

.travis.yml
binding.gyp
package.json
scripts/build_against_sdk.sh

The idea here is that you can install node-mapnik from binaries like:
```
npm install --debug --fallback-to-build=false
```
And get binaries instrumented such that backtraces are detailed with line numbers.
Closes #606
/cc @flippmoke @yhahn @mapsam

Add building/testing/publishing of Debug builds

---

src/mapnik_image.cpp
src/mapnik_projection.cpp
src/mapnik_vector_tile.cpp

These spelling errors were reported by the lintian QA tool for the Debian package build:
paramter      -> parameter
intialization -> initialization
orginal       -> original

Fix spelling errors.

---

lib/mapnik.js
src/mapnik_geometry.cpp
test/geometry.test.js

Closes #670.
cc @springmeyer.
I was unable to get the documentation generated locally (Am I missing something? Is there a particular `documentation` version you need globally installed?), but tried adding a docblock comment to the relevant `*.cpp` file.

Add Geometry#typeName method [publish docs]

---

.travis.yml

Remove the `DOC_JOB` env variable since we are no longer running docs via commit messages.

no more DOC_JOB

---

package.json
src/mapnik_datasource.cpp
src/mapnik_memory_datasource.cpp
src/mapnik_vector_tile.cpp
test/data/parse.error.json
test/datasource.test.js
test/feature.test.js

We want to consistently make `ds.featureset()` return `undefined` if a featureset is empty. This is how node-mapnik has worked for a while, but this upstream change (https://github.com/mapnik/mapnik/commit/75781a999c33afb0d54041a1208d3cc475dec8e4) altered the behavior temporarily: it meant that empty featuresets would come through as valid JS Featureset objects and you would need to call `fs.next()` to see if they were empty.
This PR keeps back compatibility and add tests for this behavior.

[WIP] consistency for empty featuresets

---

src/mapnik_vector_tile.cpp

Just a quick explicit addition to the `mapnik.VectorTile.addGeoJSON()` method that states the incoming GeoJSON datasource must be in WGS84 lat/lng.
refs #693 which would have benefited from improved docs

add crs to addGeoJSON docs

---

package.json
src/mapnik_plugins.hpp
src/node_mapnik.cpp

Adding docs for `Plugins` (faked it out as a `@class`) object. This resolves some documentation needs for #695 
The `src/mapnik_plugins.hpp` file isn't captured in documentation.js, so also had to add that single file to the `npm run docs` command for it to work. I'll make changes to our documentation generator accordingly.
cc @springmeyer @artemp

mapnik plugin docs

---

src/mapnik_image.cpp
test/image.svg.test.js

Currently it is possible for `image.fromSVG` or `image.fromSVGBytes` to allocate an unreasonably large image internally for rasterizing (which would likely lead to an OOM killer on linux). To allow programs to limit this size before this internal image is allocated there is now:
- A default max size of an SVG 2046x2046
- A new `max_size` option that can be passed to change this default value.
Addresses #708
/cc @mapsam @jakepruitt for code review (if either of you have time)
/cc @scothis @tmcw to keep apprised of work

Limit image size in image.fromSVG and image.fromSVGBytes

---

test/datasource.test.js

When built against mapnik 3.0.13 the test for parsing empty geojson from a file is now throwing:
```
1) mapnik.Datasource test empty geojson datasource due to invalid json file:
Error: Failed to parse geojson feature
at Error (native)
at Context.<anonymous> (test/datasource.test.js:215:18)
```
This seems to be consistent with the behaviour of the previous test (parsing empty geojson from a string) so I'm guessing something was deliberately changed in mapnik to make this consistent?
Not sure if you'll want to take this simple patch as is, or something more complicated that allows for either behaviour...

Parsing empty GeoJSON from file now throws

---

.travis.yml
src/mapnik_image.cpp
test/image.test.js

This extends the `mapnik.Image.fromBytes` function to have more options for top performance:
- Now accepts a `premultiply:true` option that can be passed to premultiply during the byte conversion. This allows calling applications to avoid needing to premultiply in a separate step (saving on needing to enter and exit the threadpool again, which can cause contention under high load or when the threadpool is full of work)
- Adds a max_size constraint to ensure that an unreasonably large image is not allocated.

Add max_size limitation + premultiply option to fromBytes

---

Makefile
binding.gyp
install_mason.sh
package.json

#738 ported the unix build system to use mason packages for dependencies (mapnik included). However mason does not support windows, so this rolls back some changes to keep the build working on windows.
/cc @BergWerkGIS for review.
Fixes #744

Fix windows after masonization of unix build

---

README.md

Using Mapbox's spritezero which uses `~3.5.13` (therefore picks up the new 3.5.14), I'm getting: 
`22:55:30 Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by /home/vdumont/lib/node_modules/spritezero-cli/node_modules/spritezero/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik.node)`
Should a change that is impacting the toolchain requirements (ie: now a new major version of gcc) be a _patch_ bump? Shouldn't it have been minor?

Depends on GLIBCXX_3.4.21, not GLIBCXX_3.4.20

---

.travis.yml
scripts/postinstall.sh

We moved to using [mason](https://github.com/mapbox/mason/) for dependencies in #738. Mason supports the `mason link` command which places symlinks of files at predictable paths. The build then copies these over into `lib/binding` when packaging the portable node-mapnik binaries.
The symlinks were being copied rather than the actual files. This meant that, once published, the data was missing since the symlinks were "broken" (point to non existent data).
We need to ensure this bug never happens. So this PR moves to removing the `mason_packages` folder before running the node-mapnik tests. This replicates the `point to non existent data` situation during node-mapnik travis builds.
This PR also starts passing the `-L` flag to `cp` to deference the symlinks during copy to ensure we are …

Fix packaging of portable data for icu, gdal, and proj

---

appveyor.yml
common.gypi
package.json
scripts/build-appveyor.bat

We currently only support vs2015 per https://github.com/mapnik/node-mapnik#windows-specific. A common convention with node-pre-gyp modules is to allow users to pass `--toolset=v140` to opt-into binaries built with vs2015. Because node-mapnik only supports vs2015 we provide binaries for both `npm install` (no custom flag) and `npm install --toolset=v140`. This keeps back compatibility with node-mapnik versions pre v3.6.0.
Background at #756.

Publish two versions of windows binaries

---

appveyor.yml
common.gypi
package.json
scripts/build-appveyor.bat

Moves build on appveyor to use the normal (aka stock) node.exe from nodejs.org (installed using appveyor shortcuts).
- Closes https://github.com/mapnik/node-mapnik/issues/691.
- Unlocks node v6 support
TODO:

[WIP] Attempt to build on windows against stock node v4 and v6

---

install_mason.sh
package.json
src/mapnik_image.cpp

Mapnik 249d6cc

---

Makefile

This starts building mapnik.node with `-g` even in release mode to accomplish release builds with better debugging symbols for profiling and crash debugging that should have no perf impact. The binary size goes from 3 MB to 3.4 MB on OSX, which is acceptable (I assume similar on linux). 
refs https://github.com/mapbox/cpp/blob/master/glossary.md#profiling-build
#753 is an attempt at building both mapnik core and node-mapnik with debug symbols, but I am worried that will add to much size growth to libmapnik.so, so I'm pausing work in #753 and will land this instead.
/cc @GretaCB

add debugging symbols to release builds - refs #753

---

src/mapnik_color.cpp
src/mapnik_datasource.cpp
src/mapnik_feature.cpp
src/mapnik_featureset.cpp
src/mapnik_geometry.cpp
src/mapnik_grid_view.cpp
src/mapnik_image.cpp
src/mapnik_image_view.cpp
src/mapnik_layer.cpp
src/mapnik_map.cpp
src/mapnik_memory_datasource.cpp
src/mapnik_projection.cpp
src/mapnik_vector_tile.cpp

The changes in #805 were difficult to read since there were so many formatting changes and node v8 deprecation fixes mixed with mapnik 3.1 changes. So I've ported to a standalone branch here, to test, merge, and then rebase into #805. The goal is to reduce the noise in that branch to help me better review changes related to mapnik 3.1.

isolate changes unrelated to mapnik 3.1 from #805

---

scripts/postinstall.sh

This fixes the ability to build node-mapnik from source against a local mapnik installation where that mapnik installation was build with the `./bootstrap.sh` inside mapnik core. Depends on either mapnik >= 3.0.16 or latest 3.1.x
Refs https://github.com/mapnik/node-mapnik/commit/e6103a7847d29f98243e05dc2160a162fe5dcdb5

Fix building against external mapnik that uses mason packages

---

install_mason.sh
test/vector-tile.test.js

All the dependency versions for mason packages need to match what the original mason package for mapnik builds against. This fixes things for the v3.0.x branch such that the below lists both match:
- mapnik mason package: https://github.com/mapbox/mason/blob/master/scripts/mapnik/3.0.17/script.sh#L36-L56
- node-mapnik build: https://github.com/mapnik/node-mapnik/blob/3dc21b5e218b1347fb747de14ed0a4415158f3c6/install_mason.sh

Keep mason package versions in sync (v3.0.x)

---

Makefile
binding.gyp
scripts/check_glibcxx.sh
src/glibc_workaround.cpp

This solves #835 by applying a workaround (automatically enabled by the `Makefile` wrapper, disabled with a normal source build) that will avoid the `__throw_out_of_range_fmt` symbol dependence creeping into the binary when node-mapnik is compiled and linked against libstdC++-49-dev.
This can be removed when we require libstdc++-5-dev (since I think that will trigger more symbols that are >= 3.4.20 to be depended upon per https://github.com/springmeyer/glibcxx-symbol-versioning).
With this fix applied travis now reports:
```
$ ./scripts/check_glibcxx.sh
checking ./lib/binding/mapnik.node
Success: GLIBCXX_3.4.2[0-9] symbols not present in binary (as expected)
```

another attemp to fix #835

---

README.md

Now that #835 is solved, this drops the documented `GLIBCXX` requirement from `GLIBCXX_3.4.21` to `GLIBCXX_3.4.19`.
Context at https://github.com/mapnik/node-mapnik/pull/698#issuecomment-359985438
Amends #698, refs #228

README: update GLIBCXX dependency details for linux

---

README.md

It's a source of confusion, like in https://github.com/mapnik/node-mapnik/issues/825, https://github.com/mapnik/node-mapnik/issues/733.

Add a note to README about compatibility with Mapnik 3.0.x

---

.travis.yml
package.json
src/mapnik_image.cpp
src/utils.hpp
test/vector-tile.test.js

General improvements for node 10. Feel free to just cherry-pick individual commits if you are not happy with the changes.
Required:
- 8b85751 Use Nan::NewInstance instead of `->NewInstance`. If was already done, but there was a missed call.
- 1b73465 due to a change in how assert.throws works.
Nice to have:
- 002521f Use Nan::Utf8String instead of v8::String::Utf8Value.
- 74f8f0b Add Node 10 to the build matrix
General maintenance:
- 871e126 Update nan and node-pre-gyp deps

[v3.0.x] Node 10 compatibility

---

package.json
src/mapnik_vector_tile.cpp
src/utils.hpp
test/vector-tile.test.js

Added the ability to release the buffer in a VT so that an additional copy is not performed in memory.
Adds the `release` option to the `VectorTile.getData()` method which will take ownership of the buffer from the VectorTile object resulting in it being empty after it is run.
Addresses #881

Move/Release semantics for VT getData

---

src/mapnik_vector_tile.cpp

Fixing z x y order in doc. See [issue 896](https://github.com/mapnik/node-mapnik/issues/896)

VectorTile constructor: fix z x y order in example

---

CHANGELOG.md
src/mapnik_image.cpp
test/image.test.js

Made it so that non premultiplied rgba8 images can now be passed to `mapnik.Image.resize`, if the rgba8 image is non premultiplied, a non premultiplied rgba8 image is then returned from resize. Otherwise a premultiplied image is returned.

Made it so that resize can now accept non premultiplied rgba8 images

---

CHANGELOG.md
src/blend.cpp
src/blend.hpp
src/mapnik_image.cpp

Reduced the amount of copying that took place in blend and in some other image encoding operations. This should help reduce the amount of possible time that these operations could hold the event loop.

Optimize Image Encoding

---

src/mapnik_expression.cpp
src/mapnik_layer.cpp

Addresses a couple of asan warnings from code that dereferenced an object before checking if it was NULL.

Null checks

---

src/blend.cpp
src/mapnik_cairo_surface.hpp
src/mapnik_geometry.cpp
src/mapnik_grid.hpp
src/mapnik_grid_view.cpp
src/mapnik_image.cpp
src/mapnik_image.hpp
src/mapnik_image_view.cpp
src/mapnik_map.cpp
src/mapnik_map.hpp
src/mapnik_projection.hpp
src/mapnik_vector_tile.cpp
src/mapnik_vector_tile.hpp

This PR does 3 things:
As some classes had auxiliar functions to set or unset a reference before executing an async function that depended on them, but others didn't I've force all classes to have them and use them; so instead of calling `->Ref()` or `->_ref()` (which one was used was apparently random), now the code always uses `_ref()` and `_unref().
Making use of these auxiliar functions and some hooks (or printfs) I detected 2 structures that could leave some object referenced after passing through an async call, which means resource leakage.
- Some functions would set up a reference to an object (an Image for example), then do some error checking and then call the async callback. The issue appears if an error is detected after adding the reference, as it wasn't removed before …

Address resource leaks

---

.travis.yml
package.json
src/blend.cpp
src/ds_emitter.hpp
src/js_grid_utils.hpp
src/mapnik_cairo_surface.cpp
src/mapnik_color.cpp
src/mapnik_datasource.cpp
src/mapnik_expression.cpp
src/mapnik_feature.cpp
src/mapnik_featureset.cpp
src/mapnik_fonts.hpp
src/mapnik_geometry.cpp
src/mapnik_grid.cpp
src/mapnik_grid_view.cpp
src/mapnik_image.cpp
src/mapnik_image_view.cpp
src/mapnik_layer.cpp
src/mapnik_logger.cpp
src/mapnik_map.cpp
src/mapnik_memory_datasource.cpp
src/mapnik_palette.cpp
src/mapnik_plugins.hpp
src/mapnik_projection.cpp
src/mapnik_vector_tile.cpp
src/node_mapnik.cpp
src/object_to_container.hpp
src/utils.hpp
test/vector-tile.test.js

This PR does a lot of changes to update to a new NaN with node 12 compatibility. Not all changes were mandatory, as most address thing that are currently deprecated (warnings) but not removed.
The commits can (and probably should) be reviewed individually.
The most controversial is the last one (d0bff89): It appears that in node an empty vector tile `toJSON()` returns `[]` instead of `{}`, which makes more sense since it returns an empty array but I'm not sure exactly what change in node12 has triggered this change in behaviour and whether you might want to add some kind of warning in the documentation.
References https://github.com/mapnik/node-mapnik/issues/921

Node 12 compatibility

---

src/js_grid_utils.hpp
src/mapnik_grid.cpp
src/mapnik_grid_view.cpp
src/utf8.hpp
test/render_grid.test.js
test/support/grid_view.json

This pull request fixes utfgrid support that's been broken in 4.x (but not caught because of [a typo in render_grid.test.js](https://github.com/mapnik/node-mapnik/blob/master/test/render_grid.test.js#L16)). With the current (incomplete?) implementation, the strings in the `grid` array contain alternating NUL characters. Also, when code points fall outside of ASCII range, the encoding to UTF-8 isn't valid (due to the code points being written directly without being converted to variable-length code units).
Rather than reinvent the wheel for code point conversion / writing, I pulled in [utf8.h](https://github.com/sheredom/utf8.h).

Fixes utfgrid support

---

src/blend.cpp
src/mapnik_cairo_surface.cpp
src/mapnik_grid.cpp
src/mapnik_image.cpp
src/mapnik_image_from_bytes.cpp
src/mapnik_image_from_svg.cpp
src/mapnik_image_resize.cpp
src/mapnik_vector_tile.cpp
src/mapnik_vector_tile_composite.cpp
src/mapnik_vector_tile_image.cpp
test/image.svg.test.js
test/vector-tile.test.js

This is not a comprehensive audit of grammar in this repo, but does fix some simple `a` &rarr; `an` and `then` &rarr; `than` mistakes in error messages.

Fix grammar in error messages

---

binding.gyp
package.json
scripts/postinstall.sh
scripts/preinstall.sh
src/mapnik_datasource.cpp
src/mapnik_vector_tile_json.cpp
src/mapnik_vector_tile_query.cpp
src/mapnik_vector_tile_simple_valid.cpp

Core `mapnik` platform specific binaries as "optionalDependencies". 
Address NPM package size issues (ref https://github.com/mapnik/node-mapnik/issues/999 )

Mapnik core binaries
